// Generated by CoffeeScript 1.6.1
(function() {
  var ChargePU;

  $(function() {
    return new ChargePU();
  });

  ChargePU = (function() {

    function ChargePU() {
      this.cacheElements();
      this.bindingElements();
    }

    ChargePU.prototype.cacheElements = function() {
      this.$container = $('#products-list');
      return this.$product_tpl = $('#product-tpl');
    };

    ChargePU.prototype.bindingElements = function() {
      var html;
      html = Hogan.compile(this.$product_tpl.html());
      return this.$container.find('tbody').html(html.render(this.data()));
    };

    ChargePU.prototype.data = function() {
      return {
        products: [
          {
            id: 1,
            linea: "MIX",
            vol: "3L",
            producto: "CAIPIRINHA",
            precio: 23.5,
            da_p: 5,
            da_u: 0
          }, {
            id: 2,
            linea: "MIX",
            vol: "3L",
            producto: "BLUEBERRY",
            precio: 23.5,
            da_p: 5,
            da_u: 0
          }, {
            id: 3,
            linea: "MIX",
            vol: "3L",
            producto: "BERRY",
            precio: 23.5,
            da_p: 5,
            da_u: 0
          }, {
            id: 4,
            linea: "MIX",
            vol: "3L",
            producto: "PIÑA COLADA",
            precio: 23.5,
            da_p: 5,
            da_u: 0
          }
        ]
      };
    };

    return ChargePU;

  })();

}).call(this);
